export const data = [
  {
    id: 1,
    name: "UNCLAIMED DIVIDEND",
    img: "/investors/investor-banner-1.png",
    link: "unclaimed-dividend",
  },
  {
    id: 2,
    name: "SUBSIDIARY COMPANIES",
    img: "/investors/investor-banner-2.png",
    link: "subsidiary-companies",
  },
  {
    id: 3,
    name: "STATEMENT OF DEVIATION",
    img: "/investors/investor-banner-3.png",
    link: "statement-of-deviation",
  },
  {
    id: 4,
    name: "CREDIT RATING",
    img: "/investors/investor-banner-4.png",
    link: "credit-rating",
  },
  {
    id: 5,
    name: "COMPOSITION OF COMMITTEES",
    img: "/investors/investor-banner-5.png",
    link: "composition-of-committees",
  },
  {
    id: 6,
    name: "DISCLOSURES UNDER REGULATION 46 OF LODR",
    img: "/investors/investor-banner-6.png",
    link: "disclosures-under-regulation-of-46-of-lodr",
  },
  {
    id: 7,
    name: "QUARTERLY RESULTS",
    img: "/investors/investor-banner-7.png",
    link: "quarterly-results",
  },
  {
    id: 8,
    name: "ANNUAL REPORTS",
    img: "/investors/investor-banner-8.png",
    link: "annual-reports",
  },
  {
    id: 9,
    name: "SHARE HOLDING PATTERN",
    img: "/investors/investor-banner-9.png",
    link: "share-holding-pattern",
  },
  {
    id: 10,
    name: "SHARE RECONCILIATION REPORT",
    img: "/investors/investor-banner-10.png",
    link: "share-reconciliation-report",
  },
  {
    id: 11,
    name: "SECRETARIAL COMPLIANCE REPORT",
    img: "/investors/investor-banner-11.png",
    link: "secretarial-compliance-report",
  },
  {
    id: 12,
    name: "CORPORATE GOVERNANCE REPORT",
    img: "/investors/investor-banner-12.png",
    link: "corporate-goverance-report",
  },
  {
    id: 13,
    name: "POLICIES",
    img: "/investors/investor-banner-13.png",
    link: "policies",
  },
  {
    id: 14,
    name: "AGM EGM NOTICES",
    img: "/investors/investor-banner-14.png",
    link: "agm-egm-notices",
  },
  {
    id: 15,
    name: "VOTING RESULTS",
    img: "/investors/investor-banner-15.png",
    link: "voting-results",
  },
  {
    id: 16,
    name: "INVESTOR COMPLAINTS",
    img: "/investors/investor-banner-16.png",
    link: "investor-complaints",
  },
  {
    id: 17,
    name: "NEWSPAPER PUBLICATION",
    img: "/investors/investor-banner-17.jpg",
    link: "newspaper-publication",
  },
];
