export const cancerCare = [
  {
    SNo: 1,
    BrandName: "BORZOMED Injection 2mg",
    Generic: "Bortezomib 2 mg",
    Packing: "1 Vial",
  },
  {
    SNo: 2,
    BrandName: "BORZOMED Injection 3.5mg",
    Generic: "Bortezomib 3.5 mg",
    Packing: "1 Vial",
  },
  {
    SNo: 3,
    BrandName: "DASAMED Tablets 20mg",
    Generic: "Dasatanib 20 mg",
    Packing: "1*60's Bottle",
  },
  {
    SNo: 4,
    BrandName: "DASAMED Tablets 50mg",
    Generic: "Dasatanib 50 mg",
    Packing: "1*60's Bottle",
  },
  {
    SNo: 5,
    BrandName: "DASAMED Tablets 70mg",
    Generic: "Dasatanib 70 mg",
    Packing: "1*60's Bottle",
  },
  {
    SNo: 6,
    BrandName: "DASAMED Tablets 100mg",
    Generic: "Dasatanib 100 mg",
    Packing: "1*30's Bottle",
  },
  {
    SNo: 7,
    BrandName: "LEDOMED Capsules 10mg",
    Generic: "Lenalidomide 10 mg",
    Packing: "1*10's Bottle",
  },
  {
    SNo: 8,
    BrandName: "LEDOMED Capsules 15mg",
    Generic: "Lenalidomide 15 mg",
    Packing: "1*10's Bottle",
  },
  {
    SNo: 9,
    BrandName: "LEDOMED Capsules 25mg",
    Generic: "Lenalidomide 25 mg",
    Packing: "1*10's Bottle",
  },
  {
    SNo: 10,
    BrandName: "ELTROPAG Tablets 25mg",
    Generic: "Eltrombopag 25mg",
    Packing: "1*7's Strip",
  },
  {
    SNo: 11,
    BrandName: "ELTROPAG Tablets 50mg",
    Generic: "Eltrombopag 50mg",
    Packing: "1*7's Strip",
  },
  {
    SNo: 12,
    BrandName: "LENVAMED Capsules 4mg",
    Generic: "Lenvatinib Mesylate 4 mg",
    Packing: "1*10's Strip",
  },
  {
    SNo: 13,
    BrandName: "LENVAMED Capsules 10mg",
    Generic: "Lenvatinib Mesylate 10 mg",
    Packing: "1*10's Strip",
  },
  {
    SNo: 14,
    BrandName: "ABTMED Tablets 250mg",
    Generic: "Abiraterone Acetate 250 mg",
    Packing: "1*120's Bottle",
  },
  {
    SNo: 15,
    BrandName: "PALBOMED Capsules 75mg",
    Generic: "Palbociclib 75 MG",
    Packing: "1*21's Bottle",
  },
  {
    SNo: 16,
    BrandName: "PALBOMED Capsules 100mg",
    Generic: "Palbociclib 100 MG",
    Packing: "1*21's Bottle",
  },
  {
    SNo: 17,
    BrandName: "PALBOMED Capsules 125mg",
    Generic: "Palbociclib 125 MG",
    Packing: "1*21's Bottle",
  },
  {
    SNo: 18,
    BrandName: "ABTAXOMED Injection 100mg",
    Generic: "Albumin-Bound Paclitaxel 100 mg",
    Packing: "1 Vial",
  },
  {
    SNo: 19,
    BrandName: "FASVIVO PFS 250mg",
    Generic: "Fulvestrant 250 mg",
    Packing: "1 PFS",
  },
  {
    SNo: 20,
    BrandName: "CAPAMED Tablets 500mg",
    Generic: "Capecitabine 500 mg",
    Packing: "1*10's Strip",
  },
  {
    SNo: 21,
    BrandName: "PAZOCAM Tablets 200mg",
    Generic: "Pazopanib HCl 200 mg",
    Packing: "1*30's Bottle",
  },
  {
    SNo: 22,
    BrandName: "PAZOCAM Tablets 400mg",
    Generic: "Pazopanib HCl 400 mg",
    Packing: "1*30's Bottle",
  },
  {
    SNo: 23,
    BrandName: "RAXITINIB Tablets 5mg",
    Generic: "Axitinib 5 mg",
    Packing: "1*14's Bottle",
  },
  {
    SNo: 24,
    BrandName: "AFMED Tablets 20mg",
    Generic: "Afatinib 20 mg",
    Packing: "1*28's Bottle",
  },
  {
    SNo: 25,
    BrandName: "AFMED Tablets 30mg",
    Generic: "Afatinib 30 mg",
    Packing: "1*28's Bottle",
  },
  {
    SNo: 26,
    BrandName: "AFMED Tablets 40mg",
    Generic: "Afatinib 40mg",
    Packing: "1*28's Bottle",
  },
  {
    SNo: 27,
    BrandName: "ETBMED Tablets 100mg",
    Generic: "Erlotinib HCl 100 mg",
    Packing: "1*30's Bottle",
  },
  {
    SNo: 28,
    BrandName: "ETBMED Tablets 150mg",
    Generic: "Erlotinib HCl 150 mg",
    Packing: "1*30's Bottle",
  },
  {
    SNo: 29,
    BrandName: "PEMETOMED Injection 100mg",
    Generic: "Pemetrexed 100 mg",
    Packing: "1 Vial",
  },
  {
    SNo: 30,
    BrandName: "PEMETOMED Injection 500mg",
    Generic: "Pemetrexed 500 mg",
    Packing: "1 Vial",
  },
  {
    SNo: 31,
    BrandName: "TEMO-GBM Capsules 20mg",
    Generic: "Temozolomide 20 mg",
    Packing: "1*5's Bottle",
  },
  {
    SNo: 32,
    BrandName: "TEMO-GBM Capsules 100mg",
    Generic: "Temozolomide 100 mg",
    Packing: "1*5's Bottle",
  },
  {
    SNo: 33,
    BrandName: "TEMO-GBM Capsules 250mg",
    Generic: "Temozolomide 250 mg",
    Packing: "1*5's Bottle",
  },
  {
    SNo: 34,
    BrandName: "PAC-MED Injection 30mg",
    Generic: "Paclitaxel 30 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 35,
    BrandName: "PAC-MED Injection 100mg",
    Generic: "Paclitaxel 100 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 36,
    BrandName: "PAC-MED Injection 260mg",
    Generic: "Paclitaxel 260 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 37,
    BrandName: "MED-CARB Injection 150mg",
    Generic: "Carboplatin 150 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 38,
    BrandName: "MED-CARB Injection 450mg",
    Generic: "Carboplatin 450 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 39,
    BrandName: "GEMIVO Injection 200mg",
    Generic: "Gemcitabine 200 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 40,
    BrandName: "GEMIVO Injection 1000mg",
    Generic: "Gemcitabine 1000 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 41,
    BrandName: "OXALVO Injection 50mg",
    Generic: "Oxaliplatin 50 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 42,
    BrandName: "OXALVO Injection 100mg",
    Generic: "Oxaliplatin 100 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 43,
    BrandName: "AZACAMEN Injection 100mg",
    Generic: "Azacitidine 100 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 44,
    BrandName: "APREMED KIT Capsules 125/80mg",
    Generic: "Aprepitant 125/80 mg Capsules",
    Packing: "Kit (1 cap of 125mg & 2 caps of 80mg)",
  },
  {
    SNo: 45,
    BrandName: "CARFILOMED Injection 60mg",
    Generic: "Carfilozomib 60 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 46,
    BrandName: "ENZAMED Capsules 40mg",
    Generic: "Enzalutamide 40 mg Cap",
    Packing: "1*28's Strip",
  },
  {
    SNo: 47,
    BrandName: "ENZAMED Tablets 160mg",
    Generic: "Enzalutamide 160 mg Tab",
    Packing: "1*7's Strip",
  },
  {
    SNo: 48,
    BrandName: "FOSAPREMED Injection 150mg",
    Generic: "Fos-Aprepitant 150 mg Injection",
    Packing: "1 Vial",
  },
  {
    SNo: 49,
    BrandName: "FEMMEOLA Tablets 150mg",
    Generic: "Olaparib 150mg",
    Packing: "1*30's Bottle",
  },
  {
    SNo: 50,
    BrandName: "FEMMEOLA Tablets 150mg",
    Generic: "Olaparib 150mg",
    Packing: "1*60's Bottle",
  },
  {
    SNo: 51,
    BrandName: "FEMMEOLA Tablets 150mg",
    Generic: "Olaparib 150mg",
    Packing: "1*120's Bottle",
  },
  {
    SNo: 52,
    BrandName: "FEMMEOLA Tablets 100mg",
    Generic: "Olaparib 100mg",
    Packing: "1*30's Bottle",
  },
];
